# A sample Gemfile
source "https://rubygems.org"

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'sinatra-activerecord'
# 絶対必要！
gem 'bcrypt'
group :development do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end
